name: Generate Docs Data

on:
  push:
    branches:
      - main
    paths:
      - 'code_examples/**'
      - 'docs/scripts/generate_site_data.py'
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  generate_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full Git history
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pyyaml
          
      - name: Generate site data
        run: python docs/scripts/generate_site_data.py
        
      - name: Create Pull Request if data changed
        id: create-pr
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated update: Regenerated site data"
          title: "Update generated site data"
          body: "Automatically generated updates to site data based on code changes"
          branch: "update/site-data"
          delete-branch: true
          labels: "automated"
          
      - name: Direct commit for small changes
        if: steps.create-pr.outputs.pr-number == ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/site_data.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: Regenerated site data [skip ci]"
            git push
          fi